# Generated by Django 5.2.1 on 2025-05-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_ussd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicavailability',
            name='appointment_type',
            field=models.CharField(choices=[('Checkup', 'Checkup'), ('Cleaning', 'Cleaning'), ('Filling', 'Filling')], max_length=50),
        ),
    ]
