# Generated by Django 5.2.1 on 2026-03-17 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_ussd', '0002_alter_patient_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Checkup', 'Checkup'), ('Cleaning', 'Cleaning'), ('Filling', 'Filling'), ('Extraction', 'Extraction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
